### ISSUE TITLE
No tags are getting created

### ISSUE THREAD

**Issue by ros3bud** [activeprospect/leadconduit-integration-homesdotcom#6]
When I ran cut-release 0.1.2 I got a message which said: Could not list git tags. The version was also not updated.

Same as https://github.com/activeprospect/leadconduit-integration-billsdotcom/issues/32

**Comment by alexkwolfe** [comment]
What happens when you run `git tag`?

**Comment by alexkwolfe** [comment]
I think this is the issue: https://github.com/activeprospect/cut-release/issues/1

**Comment by alexkwolfe** [comment]
This should be fixed in 0.3.10 of cut-release.
